// Package swagger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package swagger

// BadRequestError defines model for BadRequestError.
type BadRequestError struct {
	Error *string `json:"error,omitempty"`
}

// OrderResponse defines model for OrderResponse.
type OrderResponse struct {
	Message *string `json:"message,omitempty"`
}

// FindOrdersJSONBody defines parameters for FindOrders.
type FindOrdersJSONBody struct {
	ProjectId *int `json:"project_id,omitempty"`
	ReturnId  *int `json:"return_id,omitempty"`
}

// FindOrdersParams defines parameters for FindOrders.
type FindOrdersParams struct {
	Hoge          *string `form:"hoge,omitempty" json:"hoge,omitempty"`
	Authorization *string `json:"Authorization,omitempty"`
}

// FindOrdersJSONRequestBody defines body for FindOrders for application/json ContentType.
type FindOrdersJSONRequestBody FindOrdersJSONBody
