// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// OrdersOrderIDPost implements POST /orders/{order_id} operation.
//
// This endpoint processes a specific order, identified by `order_id`, with additional details
// provided in the request body.
//
// POST /orders/{order_id}
func (UnimplementedHandler) OrdersOrderIDPost(ctx context.Context, req *OrdersOrderIDPostReq, params OrdersOrderIDPostParams) (r OrdersOrderIDPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
