// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// OrdersOrderIDPostParams is parameters of POST /orders/{order_id} operation.
type OrdersOrderIDPostParams struct {
	// The unique identifier of the order (e.g., 'gmo-xxxx').
	OrderID string
}

func unpackOrdersOrderIDPostParams(packed middleware.Parameters) (params OrdersOrderIDPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_id",
			In:   "path",
		}
		params.OrderID = packed[key].(string)
	}
	return params
}

func decodeOrdersOrderIDPostParams(args [1]string, argsEscaped bool, r *http.Request) (params OrdersOrderIDPostParams, _ error) {
	// Decode path: order_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.OrderID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
