// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// OrdersOrderIDPost implements POST /orders/{order_id} operation.
	//
	// This endpoint processes a specific order, identified by `order_id`, with additional details
	// provided in the request body.
	//
	// POST /orders/{order_id}
	OrdersOrderIDPost(ctx context.Context, req *OrdersOrderIDPostReq, params OrdersOrderIDPostParams) (OrdersOrderIDPostRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
